version: '3.7'
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # - ${SERVER_PORT}:${SERVER_PORT}
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todoist
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_USER: ${DB_USERNAME}
      # POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:
    driver: bridge

volumes:
  pgdata:
